// Generated by CoffeeScript 1.3.3
(function() {
  var Log, config, logger, loggly, logglyInputName, logglyInputToken, logglySubdomain, winston;

  winston = require('winston');

  config = require('config');

  require('winston-loggly');

  loggly = config.Loggly != null;

  if (loggly) {
    logglySubdomain = config.Loggly.Subdomain;
    logglyInputName = config.Loggly.InputName;
    logglyInputToken = config.Loggly.InputToken;
    console.log("gg - " + logglySubdomain);
  }

  logger = new winston.Logger();

  logger.add(winston.transports.Console, {
    level: 'silly',
    colorize: true,
    timestamp: true
  });

  if (loggly) {
    logger.add(winston.transports.Loggly, {
      subdomain: logglySubdomain,
      inputName: logglyInputName,
      inputToken: logglyInputToken
    });
  }

  Log = (function() {

    function Log(prefix) {
      this.prefix = prefix;
      this.logger = logger;
    }

    Log.prototype.info = function(msg, meta) {
      return this.logger.info("" + this.prefix + " - " + msg, meta);
    };

    Log.prototype.debug = function(msg, meta) {
      return this.logger.debug("" + this.prefix + " - " + msg, meta);
    };

    Log.prototype.error = function(msg, meta) {
      return this.logger.error("" + this.prefix + " - " + msg, meta);
    };

    return Log;

  })();

  module.exports = function(p) {
    return new Log(p);
  };

}).call(this);
